version: "3.5"
services:
    infscroll_example:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PAGINATION_STEPS=10
        volumes:
            - ./resources/uwsgi.ini:/etc/uwsgi.ini:ro
        ports:
            - "8000:8000"
        image: infscroll_example:0.1.6



